<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="RAJESH" name="Default test" tests="7" failures="1" timestamp="11 Feb 2024 14:09:10 GMT" time="271.957" errors="0">
  <testcase name="verifyContactsPageLabel" time="0.189" classname="com.crm.qa.testcases.ContactsPageTest">
    <failure type="java.lang.AssertionError" message="User name is not valid expected [Raj Adhikari] but found [Contacts]">
      <![CDATA[java.lang.AssertionError: User name is not valid expected [Raj Adhikari] but found [Contacts]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:176)
	at com.crm.qa.testcases.ContactsPageTest.verifyContactsPageLabel(ContactsPageTest.java:39)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- verifyContactsPageLabel -->
  <testcase name="selectSingleContactsTest" time="0.175" classname="com.crm.qa.testcases.ContactsPageTest"/>
  <testcase name="selectMultipleContactsTest" time="0.322" classname="com.crm.qa.testcases.ContactsPageTest"/>
  <testcase name="createNewContactTest" time="8.737" classname="com.crm.qa.testcases.ContactsPageTest"/>
  <testcase name="createNewContactTest" time="8.194" classname="com.crm.qa.testcases.ContactsPageTest"/>
  <testcase name="createNewContactTest" time="8.467" classname="com.crm.qa.testcases.ContactsPageTest"/>
  <testcase name="createNewContactTest" time="9.194" classname="com.crm.qa.testcases.ContactsPageTest"/>
</testsuite> <!-- Default test -->
